SELECT
  ORTHOGRAPHY.ID,
  ORTHOGRAPHY.ALPH_ORDER,
  ORTHOGRAPHY.CHAR_DATA,
  ORTHOGRAPHY.DICTIONARY_ID,
  ORTHOGRAPHY.EXTENDED,
  ORTHOGRAPHY.CHANGE_DTTM,
  ORTHOGRAPHY.SAMPLE_WORD,
  ORTHOGRAPHY.SOUND_CONTRIBUTER AS AUDIO_CONTRIBUTOR,
  ORTHOGRAPHY.SOUND_DESCRIPTION AS AUDIO_DESCR,
  ORTHOGRAPHY.SOUND_MEDIA_FILENAME AS AUDIO_FILENAME,
  ORTHOGRAPHY.SOUND_RECORDER AS AUDIO_RECORDER,
  ORTHOGRAPHY.SOUND_STATUS_ID AS AUDIO_STATUS,
  ORTHOGRAPHY.UPPER_CASE_CHAR_DATA,
  ORTHOGRAPHY.WORD_ENTRY_ID,
  
  -- DIALECT
  DICTIONARY.NAME AS DIALECT, DICTIONARY.ID AS DIALECT_ID, DICTIONARY.PUBLIC_ACCESS AS DIALECT_PUBLISHED, DICTIONARY.STATUS_ID AS DIALECT_STATUS,
  DICTIONARY.DOMINANT_LANGUAGE AS DOMINANT_LANGUAGE, DICTIONARY.DESCR AS DIALECT_DESCR, DICTIONARY.CHANGE_DTTM AS DIALECT_CHANGE_DATE,
  CASE DICTIONARY.COUNTRY_ID
	WHEN 1 THEN 'CA'
    WHEN 2 THEN 'US'
    WHEN 3 THEN 'AU'
  END AS DIALECT_COUNTRY_ID,

  -- LANGUAGE
  DICTIONARY_FAMILY.NAME AS LANGUAGE, DICTIONARY_FAMILY.STATUS_ID AS LANGUAGE_STATUS, DICTIONARY_FAMILY.ID AS LANGUAGE_ID,

  -- LANGUAGE FAMILY
  LANGUAGE_GROUP.DESCR AS FAMILY, LANGUAGE_GROUP.ID AS FAMILY_ID
    
FROM FIRSTVOX.ORTHOGRAPHY
LEFT JOIN FIRSTVOX.DICTIONARY ON (ORTHOGRAPHY.DICTIONARY_ID = DICTIONARY.ID)
LEFT JOIN FIRSTVOX.LANGUAGE_GROUP ON (DICTIONARY.LANG_GRP_ID = LANGUAGE_GROUP.ID)
LEFT JOIN FIRSTVOX.DICTIONARY_FAMILY ON (DICTIONARY.LANGUAGE_FAMILY_ID = DICTIONARY_FAMILY.ID);