SELECT 
  ID, CODE, DESCR, DICTIONARY_ID, IS_PRIVATE, PARENT_CATEGORY, CODEFR, DESCRFR, IMAGE_FILENAME
FROM FIRSTVOX.WORD_CATEGORY
WHERE DICTIONARY_ID IS NULL AND IS_PRIVATE = 0
ORDER BY PARENT_CATEGORY ASC NULLS FIRST;