SELECT 
    PHRASE_ENTRY.ID AS PHRASE_ID, PHRASE_ENTRY.PHRASE, PHRASE_ENTRY.DOMINANT_LANGUAGE_PHRASE, PHRASE_ENTRY.CULTURAL_NOTE, PHRASE_ENTRY.CONTRIBUTER,
    PHRASE_ENTRY.REFERENCE, PHRASE_ENTRY.CHANGE_DTTM, PHRASE_ENTRY.ASSIGNED_USR_ID, PHRASE_ENTRY.AVAILABLE_IN_CHILDRENS_ARCHIVE, PHRASE_ENTRY.STATUS_ID AS PHRASE_STATUS,
    PHRASE_ENTRY.CATEGORY_ID, PHRASE_CATEGORY.CODE AS CATEGORY_NAME,
    ENTRY_IMAGE.FILENAME AS IMG_FILENAME, ENTRY_IMAGE.ID AS IMG_ID, ENTRY_IMAGE.STATUS_ID AS IMG_STATUS,
    ENTRY_IMAGE.DESCR AS IMG_DESCR, ENTRY_IMAGE.IS_SHARED AS IMG_SHARED, ENTRY_IMAGE.RECORDER AS IMG_RECORDER,
    ENTRY_IMAGE.ASSIGNED_USR_ID AS IMG_USER_ID, ENTRY_IMAGE.CONTRIBUTER AS IMG_CONTRIBUTOR,
    ENTRY_VIDEO.FILENAME AS VIDEO_FILENAME, ENTRY_VIDEO.ID AS VIDEO_ID, ENTRY_VIDEO.STATUS_ID AS VIDEO_STATUS,
    ENTRY_VIDEO.DESCR AS VIDEO_DESCR, ENTRY_VIDEO.IS_SHARED AS VIDEO_SHARED, ENTRY_VIDEO.RECORDER AS VIDEO_RECORDER,
    ENTRY_VIDEO.ASSIGNED_USR_ID AS VIDEO_USER_ID, ENTRY_VIDEO.CONTRIBUTER AS VIDEO_CONTRIBUTOR,
    ENTRY_AUDIO.FILENAME AS AUDIO_FILENAME, ENTRY_AUDIO.ID AS AUDIO_ID, ENTRY_AUDIO.STATUS_ID AS AUDIO_STATUS,
    ENTRY_AUDIO.DESCR AS AUDIO_DESCR, ENTRY_AUDIO.IS_SHARED AS AUDIO_SHARED, ENTRY_AUDIO.RECORDER AS AUDIO_RECORDER,
    ENTRY_AUDIO.ASSIGNED_USR_ID AS AUDIO_USER_ID, ENTRY_AUDIO.CONTRIBUTER AS AUDIO_CONTRIBUTOR,
  
	-- DIALECT
	DICTIONARY.NAME AS DIALECT, DICTIONARY.ID AS DIALECT_ID, DICTIONARY.PUBLIC_ACCESS AS DIALECT_PUBLISHED, DICTIONARY.STATUS_ID AS DIALECT_STATUS,
	DICTIONARY.DOMINANT_LANGUAGE AS DOMINANT_LANGUAGE, DICTIONARY.DESCR AS DIALECT_DESCR, DICTIONARY.CHANGE_DTTM AS DIALECT_CHANGE_DATE,
	CASE DICTIONARY.COUNTRY_ID
		WHEN 1 THEN 'CA'
	    WHEN 2 THEN 'US'
	    WHEN 3 THEN 'AU'
	END AS DIALECT_COUNTRY_ID,
	    
	DICTIONARY.REGION AS DIALECT_REGION,		
		
	-- LANGUAGE
	DICTIONARY_FAMILY.NAME AS LANGUAGE, DICTIONARY_FAMILY.STATUS_ID AS LANGUAGE_STATUS, DICTIONARY_FAMILY.ID AS LANGUAGE_ID,

	-- LANGUAGE FAMILY
	LANGUAGE_GROUP.DESCR AS FAMILY, LANGUAGE_GROUP.ID AS FAMILY_ID

FROM FIRSTVOX.PHRASE_ENTRY
LEFT JOIN FIRSTVOX.DICTIONARY ON (PHRASE_ENTRY.DICTIONARY_ID = DICTIONARY.ID)
LEFT JOIN FIRSTVOX.LANGUAGE_GROUP ON (DICTIONARY.LANG_GRP_ID = LANGUAGE_GROUP.ID)
LEFT JOIN FIRSTVOX.DICTIONARY_FAMILY ON (DICTIONARY.LANGUAGE_FAMILY_ID = DICTIONARY_FAMILY.ID)
LEFT JOIN FIRSTVOX.ENTRY_MEDIA ENTRY_IMAGE ON (ENTRY_IMAGE.ID = PHRASE_ENTRY.IMAGE_ENTRY_ID)
LEFT JOIN FIRSTVOX.ENTRY_MEDIA ENTRY_VIDEO ON (ENTRY_VIDEO.ID = PHRASE_ENTRY.VIDEO_ENTRY_ID)
LEFT JOIN FIRSTVOX.ENTRY_MEDIA ENTRY_AUDIO ON (ENTRY_AUDIO.ID = PHRASE_ENTRY.SOUND_ENTRY_ID)
LEFT JOIN FIRSTVOX.PHRASE_CATEGORY ON (PHRASE_CATEGORY.ID = PHRASE_ENTRY.CATEGORY_ID);
