SELECT 
  DICTIONARY.ID AS DIALECT_ID,
  DICTIONARY.NAME AS DIALECT,
  DICTIONARY.PORTAL_ABOUT_TEXT,
  DICTIONARY.PORTAL_GREETING,
  DICTIONARY.PORTAL_RELATED_LINKS,
  DICTIONARY.PORTAL_THEME_ID,
  DICTIONARY.FIRST_WORD_ONE_ID,
  DICTIONARY.FIRST_WORD_TWO_ID,
  DICTIONARY.FIRST_WORD_THREE_ID,
  DICTIONARY.FIRST_WORD_FOUR_ID,
  DICTIONARY.FIRST_WORD_FIVE_ID,
  DICTIONARY.IMAGE_MEDIA_FILENAME AS IMG_FILENAME,
  DICTIONARY.IMAGE_CONTRIBUTER AS IMG_CONTRIBUTOR,
  DICTIONARY.IMAGE_RECORDER AS IMG_RECORDER,
  DICTIONARY.SOUND_MEDIA_FILENAME AS AUDIO_FILENAME,
  DICTIONARY.SOUND_CONTRIBUTER AS AUDIO_CONTRIBUTOR,
  DICTIONARY.SOUND_RECORDER AS AUDIO_RECORDER,
  THEME.BACKGROUND_TOP_FILENAME,
  THEME.BACKGROUND_BOTTOM_FILENAME,
  
  -- DIALECT
  DICTIONARY.PUBLIC_ACCESS AS DIALECT_PUBLISHED, DICTIONARY.STATUS_ID AS DIALECT_STATUS,
  DICTIONARY.DOMINANT_LANGUAGE AS DOMINANT_LANGUAGE, DICTIONARY.DESCR AS DIALECT_DESCR, DICTIONARY.CHANGE_DTTM AS DIALECT_CHANGE_DATE,
  CASE DICTIONARY.COUNTRY_ID
    WHEN 1 THEN 'CA'
	WHEN 2 THEN 'US'
	WHEN 3 THEN 'AU'
  END AS DIALECT_COUNTRY_ID,  
  
  -- LANGUAGE
  DICTIONARY_FAMILY.NAME AS LANGUAGE, DICTIONARY_FAMILY.STATUS_ID AS LANGUAGE_STATUS, DICTIONARY_FAMILY.ID AS LANGUAGE_ID,
  
  -- LANGUAGE FAMILY
  LANGUAGE_GROUP.DESCR AS FAMILY, LANGUAGE_GROUP.ID AS FAMILY_ID

FROM FIRSTVOX.DICTIONARY
LEFT JOIN FIRSTVOX.THEME ON (DICTIONARY.PORTAL_THEME_ID = THEME.ID)
LEFT JOIN FIRSTVOX.LANGUAGE_GROUP ON (DICTIONARY.LANG_GRP_ID = LANGUAGE_GROUP.ID)
LEFT JOIN FIRSTVOX.DICTIONARY_FAMILY ON (DICTIONARY.LANGUAGE_FAMILY_ID = DICTIONARY_FAMILY.ID)